spring:
  application:
    name: registry-service
server:
  port: 10086    #eureka默认端口8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false
    fetch-registry: false