server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.187.252:3306/leyou?characterEncoding=utf-8
    username: root
    password: 541590
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.itheima.item.pojo
  mapper-locations: classpath:/mappers/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka